version: '3.9'
services:
  vuln:
    build:
      context: .
      dockerfile: Dockerfile.vuln
    ports:
      - "5001:5001"
  defended:
    build:
      context: .
      dockerfile: Dockerfile.defended
    ports:
      - "5002:5002"
